nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Hackernews API
            description: Hackernews API that serves anyone. It has restricted area
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api/(?!/docs$) # Accepts routes under /api except /api/doc
